import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";
import { TrpcProvider } from "../utils/trpc-provider";
import {Nav} from '../utils/navbar';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo",
};

function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): JSX.Element {
  return (
    <ClerkProvider>
      <TrpcProvider>
        <html className="h-full bg-white" lang="en">
          <body className={`${inter.className} h-full`}>
            <Nav/>
            {children}
          </body>
        </html>
      </TrpcProvider>
   </ClerkProvider>
  );
}

export default RootLayout;