import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";
import { TrpcProvider } from "../utils/trpc-provider";
import { ApplicationLayout } from "./application-layout";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo",
};

function RootLayout({ children }: { children: React.ReactNode }): JSX.Element {
  return (
    <ClerkProvider>
      <TrpcProvider>
        <html
          lang="en"
          className="text-zinc-950 antialiased lg:bg-zinc-100 dark:bg-zinc-900 dark:text-white dark:lg:bg-zinc-950"
        >
          <head>
            <link rel="preconnect" href="https://rsms.me/" />
            <link rel="stylesheet" href="https://rsms.me/inter/inter.css" />
          </head>
          <body>
            <ApplicationLayout>{children}</ApplicationLayout>
          </body>
        </html>
      </TrpcProvider>
    </ClerkProvider>
  );
}

export default RootLayout;
